#!/bin/sh

git clone https://github.com/kybr/nativefiledialog
pushd nativefiledialog/build/gmake_macosx
make
popd
cp nativefiledialog/build/lib/Release/x64/libnfd.a .
cp nativefiledialog/src/include/nfd.h .
