#!/bin/sh

git clone https://github.com/mlabbe/nativefiledialog
pushd nativefiledialog/build/gmake_macosx
make
popd
mv nativefiledialog/build/lib/Release/x64/libnfd.a .
mv nativefiledialog/src/include/nfd.h .
